Repository eecs485staff/primer-spec, pull requests merged in 2020-09, with the labels that each got.

#70 Improve accessibility (a11y) for screen-readers
  _sass/spec/base.scss
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/components/MainContent.tsx
  src_js/components/PrimerSpec.tsx
  src_js/components/Settings.tsx
  src_js/components/Topbar.tsx
  src_js/components/common/InlineButton.tsx
  src_js/components/sidebar/Sidebar.tsx
  src_js/components/sidebar/TableOfContents.tsx
Labels: enhancement, semver/minor

#71 Add jemoji to receommended plugins
  README.md
  docs/USAGE_ADVANCED.md
Labels: docs

#73 Remove unnecessary stylesheet injection
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/main.tsx
Labels: semver/patch

#72 Enable task-lists and persist the checkbox state
  assets/v1.4/js/primer_spec_plugin.min.js
  demo/task-lists.md
  index.md
  src_js/components/MainContent.tsx
  src_js/utils/Storage.ts
Labels: enhancement, semver/patch

#76 Save the state of the sidebar-shown value
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/Config.ts
  src_js/components/PrimerSpec.tsx
Labels: enhancement, semver/patch

#77 Fix for issue of sidebar not closing on mobile.
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/components/sidebar/TableOfContents.tsx
Labels: bug, semver/patch

#78 Integrate ESLint
  .eslintrc
  assets/v1.4/js/primer_spec_plugin.min.js
  package-lock.json
  package.json
  primer-spec.code-workspace
  script/cibuild
  src_js/Config.ts
  src_js/components/MainContent.tsx
  src_js/components/PrimerSpec.tsx
  src_js/components/Settings.tsx
  src_js/components/Topbar.tsx
  src_js/components/common/InlineButton.tsx
  src_js/components/sidebar/Sidebar.tsx
  src_js/components/sidebar/TableOfContents.tsx
  src_js/components/sidebar/unflattenHeadings.ts
  src_js/global.d.ts
  src_js/subthemes/createSubtheme.ts
  src_js/subthemes/index.ts
  src_js/subthemes/rouge_themes/createRougeTheme.ts
  src_js/subthemes/rouge_themes/monokai.rouge.ts
  src_js/utils/Storage.ts
  src_js/utils/getChromeVersion.ts
  src_js/utils/hooks.ts
  src_js/utils/isSmallScreen.ts
  tsconfig.json
Labels: semver/patch

#79 Add support for favicons
  _layouts/default.html
  _layouts/spec.html
  docs/USAGE_ADVANCED.md
Labels: enhancement, semver/minor

#81 Add JSX-A11y ESLint plugin
  .eslintrc
  assets/v1.4/js/primer_spec_plugin.min.js
  package-lock.json
  package.json
  src_js/components/Settings.tsx
  src_js/components/sidebar/Sidebar.tsx
  src_js/components/sidebar/TableOfContents.tsx
Labels: semver/patch

#80 Preserve code-spans from headings in Sidebar ToC
  _sass/spec/base.scss
  assets/v1.4/js/primer_spec_plugin.min.js
  index.md
  src_js/components/sidebar/TableOfContents.tsx
Labels: enhancement, semver/patch

#82 Add source comments and console log to improve repo discoverability
  _layouts/spec.html
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/main.tsx
Labels: semver/patch

#83 Fix code smells in `subthemes/index.ts`
  assets/v1.4/js/primer_spec_plugin.min.js
  src_js/components/PrimerSpec.tsx
  src_js/components/Settings.tsx
  src_js/main.tsx
  src_js/subthemes/index.ts
Labels: semver/patch

#84 [RFC] Prevent long headings from increasing Sidebar's width
  _sass/spec/base.scss
  demo/long-headings.md
Labels: semver/minor
